# Site settings
title: Portfolio Peter van Sark
email: peter@vansark.com
author: Peter van Sark
description: Portfolio website of Peter van Sark
url: http://petervansark.github.io/
permalink: /:categories/:title:output_ext

# Build settings
lay-out: default 
permalin: :title/
exclude: 
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules
  - .gitignore
  - _sass
  - assets/src

 plugins:
  - jemoji